TARGET   := platformer

# directories
SRCDIR   := src
BUILDDIR := build
LIBDIR   := lib

# compiler options
CC 		 := cc
INC      := -I$(LIBDIR)/glfw/include -I$(LIBDIR)/glad/include -I$(LIBDIR)/stb_image/ -I$(SRCDIR)
CFLAGS   := -Wall -Wextra -Og -g $(INC)
LDFLAGS  := $(LIBDIR)/glfw/src/libglfw3.a $(LIBDIR)/glad/glad.o $(LIBDIR)/stb_image/stb_image.o -lm -ldl -lrt -lpthread


SRC := $(shell find $(SRCDIR) -name "*.c")
OBJ := $(patsubst $(SRCDIR)/%.c, $(BUILDDIR)/%.o, $(SRC))
DEP := $(OBJ:%.o=%.d)

all: lib $(BUILDDIR)/$(TARGET)

run: all
	$(BUILDDIR)/./$(TARGET)

# header file dependencies generated by compiler.
-include $(DEP)

$(BUILDDIR)/$(TARGET): $(OBJ)
	$(CC) $^ -o $@  $(LDFLAGS)

# build libraries required.
lib: $(LIBDIR)/glfw/src/libglfw3.a $(LIBDIR)/glad/glad.o $(LIBDIR)/stb_image/stb_image.o

$(LIBDIR)/glfw/src/libglfw3.a:
	cd $(LIBDIR)/glfw && cmake . && make

$(LIBDIR)/glad/glad.o:
	cd $(LIBDIR)/glad && $(CC) -o glad.o -Iinclude -c src/gl.c

$(LIBDIR)/stb_image/stb_image.o:
	cd $(LIBDIR)/stb_image && $(CC) -o stb_image.o -c stb_image.c

# building object files from source files.
$(BUILDDIR)/%.o: $(SRCDIR)/%.c
	mkdir -p $(@D)
	$(CC) -MMD -MP -c $< -o $@ $(CFLAGS)

clean:
	rm -rf $(BUILDDIR)

.PHONY: all clean lib
